/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.snake;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import static java.lang.Class.forName;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author shadin
 */
public class Login extends javax.swing.JFrame  {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        signin = new com.k33ptoo.components.KButton();
        signup = new com.k33ptoo.components.KButton();
        Login = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 0, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("username");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 80, -1));

        username.setBackground(new java.awt.Color(102, 102, 102));
        username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        username.setOpaque(true);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 270, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, -1));

        password.setBackground(new java.awt.Color(102, 102, 102));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.setOpaque(true);
        kGradientPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 270, 30));

        signin.setText("sign in");
        signin.setkBackGroundColor(new java.awt.Color(0, 153, 204));
        signin.setkBorderRadius(-20);
        signin.setkEndColor(new java.awt.Color(153, 0, 153));
        signin.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        signin.setkHoverStartColor(new java.awt.Color(204, 0, 204));
        signin.setkPressedColor(new java.awt.Color(102, 102, 102));
        kGradientPanel1.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 90, 30));

        signup.setText("sign up");
        signup.setkBackGroundColor(new java.awt.Color(0, 153, 204));
        signup.setkBorderRadius(-20);
        signup.setkEndColor(new java.awt.Color(153, 0, 153));
        signup.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        signup.setkHoverStartColor(new java.awt.Color(0, 51, 204));
        signup.setkPressedColor(new java.awt.Color(102, 102, 102));
        signup.setkSelectedColor(new java.awt.Color(153, 0, 153));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        kGradientPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 90, 30));

        Login.setText("Login");
        Login.setkBackGroundColor(new java.awt.Color(51, 153, 255));
        Login.setkBorderRadius(20);
        Login.setkEndColor(new java.awt.Color(204, 0, 204));
        Login.setkFillButton(false);
        Login.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        Login.setkHoverStartColor(new java.awt.Color(0, 0, 153));
        Login.setkPressedColor(new java.awt.Color(102, 102, 102));
        Login.setkSelectedColor(new java.awt.Color(0, 102, 153));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 90, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Snake","root","");
            String sql= "Select * from Snake WHere username=? and password=?";
            PreparedStatement pst= con.prepareStatement(sql);
            pst.setString(1, username.getText());
            pst.setString (2, password.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
               new GameFrame().setVisible(true);
                
                
            }
            
            else{
                JOptionPane.showMessageDialog(null,"Incorrect username or password!");
                username.setText("");
                password.setText("");
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_LoginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:   
            RegistrationForm rf = new RegistrationForm();
            rf.setVisible(true);
            rf.pack();
            rf.setLocationRelativeTo(null);
            rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField password;
    private com.k33ptoo.components.KButton signin;
    private com.k33ptoo.components.KButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
